### ISSUE TITLE
Heart Relay

### ISSUE THREAD

**Issue by codeviolet** [VirtualDisgrace/heart-r8#1]
Hello. I'm hoping this the right code repository and place for questions about the scripts used in the "Heart Relay" (1.2.8) provided in SL...

Wondering if the RLV protocol for ["ping/!pong"](http://wiki.secondlife.com/wiki/LSL_Protocol/Restrained_Love_Relay/Specification#.22ping.22_relay_message_and_.22.21pong.22_object_meta-command) is working as expected in the Heart Relay, as I have a [report](https://avsitter.com/qa/955) that it is not functioning as expected, whereas the main OC relay implementation does seem to work (and has for several years). Thanks.

**Comment by WendyStarfall** [comment]
Heart R8 as a Turbo Relay derivative, was intended as a light, fast and playful device.

Something that's useful for busy roleplay sites or places with traps or other furniture that grabs avatars, so to play with them *right now*, but not to keep them locked down persistently over multiple SL sessions.

Once an avatar logged out, playtime is over until going on a new adventure the next time when online! :tada:

It's been a while that I obsessed over this particular relay but to the best of my knowledge the ORG (Open Relay Group) extensions that are required for "re-capture" would slow the device down significantly.

Based on feedback, Heart R8 appears to be very attractive to users who even explicitly want a more playful experience and rather not wear a collar at all.

Users who desire a more persistent experience usually prefer the relay plugin that ships with OpenCollar Six.

**Comment by codeviolet** [comment]
Thank you for your reply. As the feature is listed under [Formal requirements for a RLV relay](http://wiki.secondlife.com/wiki/LSL_Protocol/Restrained_Love_Relay/Specification#Formal_requirements), I thought the Heart Relay would intend to implement it, for consistency with user expectations. Or as explained in the specification "... common rules so all the relays implementing it are compatible with all the furniture implementing it too."

But it doesn't worry me at all. It greatly helps to know the cause for the user's trouble. Thank you again for getting back so quickly.
